

-- 우유와 요거트가 담긴 장바구니

SELECT DISTINCT(C1.CART_ID)
FROM (SELECT * FROM CART_PRODUCTS WHERE NAME='MILK') AS C1 INNER JOIN
(SELECT *FROM CART_PRODUCTS WHERE NAME='YOGURT') AS C2 
WHERE C1.CART_ID = C2.CART_ID;